export const textToIcon = 
    {
        'Sunny':{icon:'CLEAR_DAY', nightIcon:'CLEAR_NIGHT',dayColor:'#F4D13B', nightColor:'#24CEEA'},
        'Mostly sunny':{icon:'CLEAR_NIGHT', nightIcon:'CLEAR_NIGHT',dayColor:'#F4D13B', nightColor:'#24CEEA'},
        'Partly sunny':{icon:'PARTLY_CLOUDY_DAY', nightIcon:'PARTLY_CLOUDY_NIGHT',dayColor:'#F4D13B', nightColor:'#24CEEA'},
        'Intermittent Clouds':{icon:'PARTLY_CLOUDY_DAY', nightIcon:'PARTLY_CLOUDY_NIGHT',dayColor:'#2DD2D6', nightColor:'#1C9B9B'},
        'Hazy sunshine':{icon:'PARTLY_CLOUDY_DAY', nightIcon:'PARTLY_CLOUDY_NIGHT',dayColor:'#F4D13B', nightColor:'#24CEEA'},
        'Mostly cloudy':{icon:'CLOUDY', nightIcon:'CLOUDY',dayColor:'#2DD2D6', nightColor:'#1C9B9B'},
        'Cloudy':{icon:'CLOUDY', nightIcon:'CLOUDY',dayColor:'#2DD2D6', nightColor:'#1C9B9B'},
        'Dreary (Overcast)':{icon:'CLOUDY', nightIcon:'CLOUDY',dayColor:'#235EA5', nightColor:'#235EA5'},
        'Fog':{icon:'FOG', nightIcon:'FOG',dayColor:'#ACBFBF', nightColor:'#999999'},
        'Showers':{icon:'SLEET', nightIcon:'SLEET',dayColor:'#4786B5', nightColor:'#235EA5'},
        'Mostly cloudy w/ showers':{icon:'PARTLY_CLOUDY_DAY', nightIcon:'PARTLY_CLOUDY_DAY',dayColor:'#4786B5', nightColor:'#235EA5'},
        'Partly sunny w/ showers':{icon:'PARTLY_CLOUDY_DAY', nightIcon:'PARTLY_CLOUDY_NIGHT',dayColor:'#F4D13B', nightColor:'#24CEEA'},
        'T-storms':{icon:'SLEET', nightIcon:'SLEET',dayColor:'#235EA5', nightColor:'#235EA5'},
        'Mostly cloudy w/ T-storms':{icon:'PARTLY_CLOUDY_DAY', nightIcon:'PARTLY_CLOUDY_DAY',dayColor:'#235EA5', nightColor:'#235EA5'},
        'Partly sunny w/ T-storms':{icon:'PARTLY_CLOUDY_DAY', nightIcon:'PARTLY_CLOUDY_NIGHT',dayColor:'#F4D13B', nightColor:'#24CEEA'},
        'Rain':{icon:'RAIN', nightIcon:'RAIN',dayColor:'#4786B5', nightColor:'#235EA5'},
        'Flurries':{icon:'PARTLY_CLOUDY_DAY', nightIcon:'',dayColor:'#235EA5', nightColor:'#235EA5'},
        'Mostly cloudy w/ flurries':{icon:'PARTLY_CLOUDY_DAY', nightIcon:'PARTLY_CLOUDY_NIGHT',dayColor:'#235EA5', nightColor:'#235EA5'},
        'Partly sunny w/ flurries':{icon:'PARTLY_CLOUDY_DAY', nightIcon:'PARTLY_CLOUDY_NIGHT',dayColor:'#235EA5', nightColor:'#235EA5'},
        'Snow':{icon:'SNOW', nightIcon:'SNOW',dayColor:'#BDC1C1', nightColor:'#BDC1C1'},
        'Mostly cloudy w/ Snow':{icon:'PARTLY_CLOUDY_DAY', nightIcon:'PARTLY_CLOUDY_NIGHT',dayColor:'#BDC1C1', nightColor:'#BDC1C1'},
        'Ice':{icon:'SNOW', nightIcon:'SNOW',dayColor:'#BDC1C1', nightColor:'#BDC1C1'},
        'Freezing rain':{icon:'SLEET', nightIcon:'SLEET',dayColor:'#4786B5', nightColor:'#235EA5'},
        'Rain and snow':{icon:'SNOW', nightIcon:'SNOW',dayColor:'#BDC1C1', nightColor:'#BDC1C1'},
        'Hot':{icon:'CLEAR_DAY', nightIcon:'CLEAR_NIGHT',dayColor:'#F4D13B', nightColor:'#24CEEA'},
        'Cold':{icon:'WIND', nightIcon:'WIND',dayColor:'#4786B5', nightColor:'#235EA5'},
        'Windy':{icon:'WIND', nightIcon:'WIND',dayColor:'#4786B5', nightColor:'#235EA5'},
        'Clear':{icon:'CLEAR_DAY', nightIcon:'CLEAR_NIGHT',dayColor:'#F4D13B', nightColor:'#24CEEA'},
        'Mostly clear':{icon:'CLEAR_DAY', nightIcon:'CLEAR_NIGHT',dayColor:'#F4D13B', nightColor:'#24CEEA'},
        'Partly cloudy':{icon:'PARTLY_CLOUDY_DAY', nightIcon:'PARTLY_CLOUDY_NIGHT',dayColor:'#235EA5', nightColor:'#235EA5'},
        'Intermittent clouds':{icon:'CLOUDY', nightIcon:'CLOUDY',dayColor:'#4786B5', nightColor:'#235EA5'},
        'Hazy moonlight':{icon:'CLEAR_NIGHT', nightIcon:'CLEAR_NIGHT',dayColor:'#235EA5', nightColor:'#235EA5'},
        'Mostly cloudy':{icon:'CLOUDY', nightIcon:'CLOUDY',dayColor:'#2DD2D6', nightColor:'#1C9B9B'},
        'Partly cloudy w/ Showers':{icon:'PARTLY_CLOUDY_DAY', nightIcon:'PARTLY_CLOUDY_NIGHT',dayColor:'#235EA5', nightColor:'#235EA5'},
        'Cloudy w/ showers':{icon:'CLOUDY', nightIcon:'CLOUDY',dayColor:'#4786B5', nightColor:'#235EA5'},
        'Partly cloudy w/ t-storms':{icon:'PARTLY_CLOUDY_DAY', nightIcon:'PARTLY_CLOUDY_NIGHT',dayColor:'#235EA5', nightColor:'#235EA5'},
        'Mostly cloudy w/ t-storms':{icon:'PARTLY_CLOUDY_DAY', nightIcon:'PARTLY_CLOUDY_NIGHT',dayColor:'#235EA5', nightColor:'#235EA5'},
        'Mostly cloudy w/ flurries':{icon:'PARTLY_CLOUDY_DAY', nightIcon:'PARTLY_CLOUDY_NIGHT',dayColor:'#235EA5', nightColor:'#235EA5'},
        'Mostly cloudy w/ snow':{icon:'PARTLY_CLOUDY_DAY', nightIcon:'PARTLY_CLOUDY_NIGHT',dayColor:'#BDC1C1', nightColor:'#BDC1C1',
        undefined:{icon:'CLEAR_DAY', nightIcon:'CLEAR_NIGHT',dayColor:'#F4D13B', nightColor:'#24CEEA'}
}
}
